In [1]:
import os
import glob
import pandas as pd
import numpy as np

brain_path = '/scratch/connectome/3DCNN/data/1.ABCD/2.sMRI_freesurfer'
phenotype_path = '/scratch/connectome/3DCNN/data/1.ABCD/4.demo_qc/ABCD_phenotype_total.csv'

In [51]:
brain_data = pd.DataFrame({'subjectkey':pd.Series(map(lambda x: x.split("/")[-1], glob.glob(brain_path+'/*.npy')))})

In [52]:
brain_data.subjectkey = brain_data.subjectkey.map(lambda x: x.split('.')[0])

In [54]:
brain_data.head()

        subjectkey
0  NDARINVBZJGG4AN
1  NDARINVXPZGM0LG
2  NDARINVU9C36KFY
3  NDARINV2FV9YY14
4  NDARINV0889M0JE

In [59]:
subject_data = pd.read_csv(phenotype_path)[['age','subjectkey','abcd_site']]

In [60]:
subject_data.shape

(11875, 3)

In [61]:
subject_data = pd.merge(brain_data,subject_data,on='subjectkey',how='inner')

In [63]:
subject_data.dropna()

            subjectkey    age  abcd_site
0      NDARINVBZJGG4AN  123.0       20.0
1      NDARINVXPZGM0LG  117.0       18.0
2      NDARINVU9C36KFY  109.0        4.0
3      NDARINV2FV9YY14  131.0        9.0
4      NDARINV0889M0JE  111.0       21.0
...                ...    ...        ...
11368  NDARINVDZVTE3N0  131.0        6.0
11369  NDARINVUW2RRYUA  108.0        5.0
11370  NDARINVG51E0KVR  112.0       11.0
11371  NDARINVYTRMF19U  128.0       19.0
11372  NDARINV4MPM83XL  109.0        4.0

[11357 rows x 3 columns]

In [64]:
subject_data.abcd_site.describe()

count    11357.000000
mean        11.455138
std          6.083301
min          1.000000
25%          6.000000
50%         12.000000
75%         16.000000
max         22.000000
Name: abcd_site, dtype: float64

In [68]:
subject_data.abcd_site.value_counts()

16.0    995
4.0     730
13.0    697
20.0    685
10.0    673
3.0     607
14.0    589
12.0    588
21.0    576
6.0     572
17.0    560
2.0     542
19.0    527
11.0    428
9.0     427
15.0    425
1.0     385
5.0     365
7.0     337
18.0    332
8.0     282
22.0     35
Name: abcd_site, dtype: int64

In [70]:
subject_data.abcd_site.value_counts().sort_index()

1.0     385
2.0     542
3.0     607
4.0     730
5.0     365
6.0     572
7.0     337
8.0     282
9.0     427
10.0    673
11.0    428
12.0    588
13.0    697
14.0    589
15.0    425
16.0    995
17.0    560
18.0    332
19.0    527
20.0    685
21.0    576
22.0     35
Name: abcd_site, dtype: int64

In [37]:
subject_data.abcd_site[0].dtype

dtype('float64')

In [32]:
import argparse
parser = argparse.ArgumentParser()
parser.add_argument("--filter",required=False, nargs="+", default=[],
                    help='options for filter data by phenotype. usage: --filter abcd_site:10 sex:1') # revising
parser.add_argument("--name",required=False, type=str, help='') # revising

_StoreAction(option_strings=['--name'], dest='name', nargs=None, const=None, default=None, type=<class 'str'>, choices=None, help='', metavar=None)

In [33]:
command = '--filter abcd_site:10 sex:1 --name test'.split()
args = parser.parse_args(args=command)

In [85]:
args.filter

['abcd_site:10', 'sex:1']

In [54]:
for fil in args.filter:
    fil_name, fil_option = fil.split(':')
    fil_option = np.float64(fil_option)
    subject_data = subject_data[subject_data[fil_name] == fil_option]

In [77]:
subject_data.abcd_site.dtype == np.float64

True

TypeError: 'module' object is not callable

In [55]:
subject_data

,subjectkey,age,sex,race.ethnicity,high.educ,income,married,abcd_site,height,weight,...,Substance.Use.Disorder.x,Other.Drugs.Use.Disorder.x,Sedative.Hypnotic.or.Anxiolytic.Use.Disorder.x,Other.Specified.Trauma.and.Stressor.Related.Disorder.x,Post.Traumatic.Stress.Disorder.x,HOMICIDAL.IDEATION.AND.BEHAVIOR.x,totalBIS,totalBAS,PPSP_frequency,PPSP_distress
32,NDARINV029PWCFY,108.0,1.0,5.0,21.0,10.0,1.0,10.0,50.500,53.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,13.0,25.0,2,0
72,NDARINV06DE9Y0L,108.0,1.0,1.0,11.0,5.0,1.0,10.0,52.000,93.000000,...,0.0,0.0,0.0,1.0,0.0,0.0,10.0,27.0,1,2
76,NDARINV06LWXY67,131.0,1.0,1.0,18.0,5.0,4.0,10.0,65.100,133.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,9.0,17.0,1,0
255,NDARINV0L7XB3AW,125.0,1.0,2.0,16.0,6.0,3.0,10.0,64.000,130.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,11.0,22.0,0,0
287,NDARINV0P3ERKVG,108.0,1.0,1.0,18.0,9.0,3.0,10.0,55.000,78.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,8.0,16.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11759,NDARINVZMMR8GE2,112.0,1.0,3.0,9.0,5.0,1.0,10.0,53.125,60.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,13.0,22.0,3,0
11805,NDARINVZTP2ZHLN,129.0,1.0,3.0,18.0,9.0,1.0,10.0,62.500,98.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,4.0,8.0,0,0
11834,NDARINVZWACXHZ6,108.0,1.0,1.0,18.0,10.0,1.0,10.0,54.000,79.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,12.0,32.0,13,17
11842,NDARINVZXC2YRV3,117.0,1.0,1.0,19.0,7.0,3.0,10.0,61.875,129.833333,...,0.0,0.0,0.0,0.0,0.0,1.0,14.0,20.0,0,0
11856,NDARINVZYRTFYRP,117.0,1.0,3.0,13.0,6.0,1.0,10.0,53.750,60.250000,...,0.0,0.0,0.0,0.0,0.0,0.0,4.0,21.0,6,5